version: "3.8"

services:
  backend:
    container_name: alx_image_api
    labels:
      - com.host.description = Node Backend for Image Processing API
    build: .
    expose:
      - 8080
    ports:
      - "8090:8080"
    working_dir: /usr/app
    restart: on-failure